### ISSUE TITLE
Setting up DOcker

### ISSUE THREAD

**Issue by mnp1791** [OCR4all/OCR4all#28] opened 2019-08-26 13:21 UTC
I still have problems setting this up (sorry, I'm not an expert)

 -v <OCR_DATA_DIR>:/var/ocr4all/data

Does the file name here refer to the folders that I set up in the beginning? 
If I input this on the command line: 

 -v <Bozner>:/var/ocr4all/data
I get an error that the system can't find the file (I have: Public - ocr34all - data Bozner)
if I input:

 -v Bozener:/var/ocr4all/data 
I get '-v' is not recognized. 

What am I doing wrong?

**Comment by NesbiDevelopment** [comment] 2019-08-26 14:53
Hello there.
I hope I understand your problem correctly, but I think the problem is one of the following.
(It looks like you are using Windows, some of the following commands will only apply to Windows)

* Is `Bozner` one of your books? If yes, then it shouldn't be included in the setup.

* The line: 
```
-v <OCR_DATA_DIR>:/var/ocr4all/data
```
is not an independent line. It's just a part of the following command (Windows)
```
docker run -p 1476:8080 -p 5000:5000 --name ocr4all \
-v <OCR_DATA_DIR>:/var/ocr4all/data \
-v <OCR_DATA_DIR>:/var/ocr4all/models/custom \
-it ls6uniwue/ocr4all
```
So you do need to type `\` and press enter <ENTER> or you could alternatively write everything in one line:
```
docker run -p 1476:8080 -p 5000:5000 --name ocr4all -v <OCR_DATA_DIR>:/var/ocr4all/data -v <OCR_MODELS_DIR>:/var/ocr4all/models/custom -it ls6uniwue/ocr4all
```

* `<OCR_DATA_DIR>` needs to be a complete file path.  
So if your books are in the data folder under `Public - ocr4all - data`, then the path should be:
`C:\Users\Public\ocr4all\data\` or 
`c/Users/Public/ocr4all/data` 
(See [setup](https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide.pdf) for which one you need)

* Example:
If your file system is as follows (file tree):
```
C:\
 └── Users
     └── Public
           └── ocr4all
                 ├── data
                 │     └── Bozner
                 │          └── input
                 │               ├── 0000.png
                 │               ├── ...
                 │               └── 0500.png
                 └── models
```
The command should be:
```
docker run -p 1476:8080 -p 5000:5000 --name ocr4all \
-v C:\Users\Public\ocr4all\data:/var/ocr4all/data \
-v C:\Users\Public\ocr4all\models:/var/ocr4all/models/custom \
-it ls6uniwue/ocr4all
```
or
```
docker run -p 1476:8080 -p 5000:5000 --name ocr4all \
-v c/Users/Public/ocr4all/data:/var/ocr4all/data \
-v c/Users/Public/ocr4all/models:/var/ocr4all/models/custom \
-it ls6uniwue/ocr4all
```

(OCR4all should afterwards be accessible if you type "localhost:1476" into your browser of choise)

I hope to have been of assistance and that this solves your issue.

----------------------------------------
And if you haven't, feel free to visit our getting started guides on [OCR4all/getting_started/](https://github.com/OCR4all/getting_started/) with comprehensive [setup](https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide.pdf) and user guides ([short](https://github.com/OCR4all/getting_started/blob/master/ocr4all-short_user_guide.pdf), [comprehensive English](https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_eng.pdf), [comprehensive German](https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_ger.pdf))

**Comment by mnp1791** [comment] 2019-08-27 06:31
Dear Nico
Thank you for your quick reply, it’s much appreciated.
For me this one applies :

The command should be:

docker run -p 1476:8080 -p 5000:5000 --name ocr4all \



-v C:\Users\Public\ocr4all\data:/var/ocr4all/data \



-v C:\Users\Public\ocr4all\models:/var/ocr4all/models/custom \



-it ls6uniwue/ocr4all


I just tried to copy this line by line but already got an error on the first one: docker: invalid reference format

Docker is installed on my private drive not on Public. Yesterday (I use docker also for something else) I closed it down with docker-compose down so I thought that might be the problem and started it again but that doesn’t seem to make a difference.

Marion


Von: Nico Balbach <notifications@github.com>
Gesendet: Montag, 26. August 2019 16:54
An: OCR4all/OCR4all <OCR4all@noreply.github.com>
Cc: Prudlo, Marion (UB) <marion.prudlo@ub.unibe.ch>; Author <author@noreply.github.com>
Betreff: Re: [OCR4all/OCR4all] Setting up DOcker (#28)


Hello there.
I hope I understand your problem correctly, but I think the problem is one of the following.
(It looks like you are using Windows, some of the following commands will only apply to Windows)

·         Is Bozner one of your books? If yes, then it shouldn't be included in the setup.

·         The line:

-v <OCR_DATA_DIR>:/var/ocr4all/data



is not an independent line. It's just a part of the following command (Windows)

docker run -p 1476:8080 -p 5000:5000 --name ocr4all \



-v <OCR_DATA_DIR>:/var/ocr4all/data \



-v <OCR_DATA_DIR>:/var/ocr4all/models/custom \



-it ls6uniwue/ocr4all



So you do need to type \ and press enter or you could alternatively write everything in one line:

docker run -p 1476:8080 -p 5000:5000 --name ocr4all -v <OCR_DATA_DIR>:/var/ocr4all/data -v <OCR_MODELS_DIR>:/var/ocr4all/models/custom -it ls6uniwue/ocr4all



·         <OCR_DATA_DIR> needs to be a complete file path.
So if your books are in the data folder under Public - ocr4all - data, then the path should be:
C:\Users\Public\ocr4all\data\ or
c/Users/Public/ocr4all/data
(See setup<https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide.pdf> for which one you need)

·         Example:
If your file system is as follows (file tree):

C:\



 └── Users



     └── Public



           └── ocr4all



                 ├── data



                 │     └── Bozner



                 │          └── input



                 │               ├── 0000.png



                 │               ├── ...



                 │               └── 0500.png



                 └── models



The command should be:

docker run -p 1476:8080 -p 5000:5000 --name ocr4all \



-v C:\Users\Public\ocr4all\data:/var/ocr4all/data \



-v C:\Users\Public\ocr4all\models:/var/ocr4all/models/custom \



-it ls6uniwue/ocr4all



or

docker run -p 1476:8080 -p 5000:5000 --name ocr4all \



-v c/Users/Public/ocr4all/data:/var/ocr4all/data \



-v c/Users/Public/ocr4all/models:/var/ocr4all/models/custom \



-it ls6uniwue/ocr4all



(OCR4all should afterwards be accessible if you type "localhost:1476" into your browser of choise)

I hope to have been of assistance and that this solves your issue.

________________________________

And if you haven't, feel free to visit our getting started guides on OCR4all/getting_started/<https://github.com/OCR4all/getting_started/> with comprehensive setup<https://github.com/OCR4all/getting_started/blob/master/ocr4all-setup_guide.pdf> and user guides (short<https://github.com/OCR4all/getting_started/blob/master/ocr4all-short_user_guide.pdf>, comprehensive English<https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_eng.pdf>, comprehensive German<https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_ger.pdf>)

**Comment by NesbiDevelopment** [comment] 2019-08-27 07:33
I'm glad I could help.
I'll close this issue then.

**Closed by NesbiDevelopment** 2019-08-27 07:33 UTC
