### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by raphink** [OCR4all/OCR4all#1] opened 2019-04-25 07:50 UTC
The README points to a `Dockerfile` in the `master` branch to build and launch the project, but the file has been removed in 134169af50a956d43d4c6aba91152fdb2a718c84. What is the status, and how do we use the project?

**Comment by NesbiDevelopment** [comment] 2019-04-25 08:20
Hello.
I'm sorry, we seem to have forgotten to update the README of this repository.
The project has been split into multiple repository and was uploaded to hub.docker.com

This repository is about the Webinterface of OCR4all, while [OCR4all/docker_image](https://github.com/OCR4all/docker_image/) and [OCR4all/docker_base_image](https://github.com/OCR4all/docker_base_image/) are about the docker file.

The README at [OCR4all/docker_image/README.md](https://github.com/OCR4all/docker_image) contains the most resent installation instructions.

In short, the docker image can be pulled with `docker pull ls6uniwue/ocr4all` and initially started with:

On Linux (you may need sudo or being in the docker user group):
```
docker run \
    -p 5000:5000 \
    -p 8080:8080 \
    -u `id -u root`:`id -g $USER` \
    --name ocr4all \
    -v <OCR_DATA_DIR>:/var/ocr4all/data \
    -v <OCR_MODEL_DIR>:/var/ocr4all/models/custom \
    -it <IMAGE_NAME>
```

On Windows/Mac:
```
docker run \
    -p 5000:5000 \
    -p 8080:8080 \
    --name ocr4all \
    -v <OCR_DATA_DIR>:/var/ocr4all/data \
    -v <OCR_MODEL_DIR>:/var/ocr4all/models/custom \
    -it <IMAGE_NAME>
```

With `<OCR_DATA_DIR>` being the folder you want to save the image, ocr and processing data on your pc and `<OCR_MODEL_DIR>` being the folder you want to save the Neural Network models on your pc.
`<IMAGE_NAME>` can be of your choosing, but we recomment `ocr4all`.

The docker image is then running and can be started on your next boot with:
`docker start -i <IMAGE_NAME>` 

Thank you for making us aware about the issue with the README in this repository.

I will keep this issue open until we've updated the README.

**Comment by raphink** [comment] 2019-04-25 08:39
Thanks for the answer. I've indeed found `ls6uniwue/ocr4all` and successfully started the image, making the model dir point to a checkout of https://github.com/OCR4all/ocr4all_models.

I've put an image in the models dir, saved as `Original/0001.png` as the interface complained otherwise. The image seems to get processed, but the report doesn't look good (imo)

![Screenshot from 2019-04-25 10-39-26](https://user-images.githubusercontent.com/650430/56722001-6e745480-6746-11e9-89d3-8babf169742c.png)

**Comment by chreul** [comment] 2019-04-25 08:46
The place to get started using OCR4all is the [getting started](https://github.com/OCR4all/getting_started) repository :-). There comprehensive guides for installation und usage.
Please have a look at the setup guide and make sure everything runs correctly. Then, I recommend to try out the provided example data which is also refernced in the user guide.

**Comment by NesbiDevelopment** [comment] 2019-04-25 08:50
I've updated the README accordingly.
You do not need to point the models dir to that checkout. The docker file will download the models from that repository by itself.

The images have to be in the data folder. A structure can be as follows:
```
.
├── data
│   └── Project
│           └── Original
│                   └── 0001.png
└── models
```

With data and models being the folders you specified  in:
```
docker run \
    -p 5000:5000 \
    -p 8080:8080 \
    --name ocr4all \
    -v <OCR_DATA_DIR>:/var/ocr4all/data \
    -v <OCR_MODEL_DIR>:/var/ocr4all/models/custom \
    -it <IMAGE_NAME>
```

With data and models being the folders you specified in `<OCR_DATA_DIR>` and `<OCR_MODEL_DIR>`

But feel free to explore the [getting started](https://github.com/OCR4all/getting_started) repository as chreul said.

**Comment by raphink** [comment] 2019-04-25 08:53
What is the point of using a volume for the models if the image downloads them?

**Comment by chreul** [comment] 2019-04-25 09:00
The image downloads a small pre selection of models which can be complemented by copying them in the model directory. Furthermore, models you trained yourself will be made availabe there.

**Comment by raphink** [comment] 2019-04-25 09:06
OK, so I'm providing an empty directory for the models (and it doesn't get filled automatically from what I can tell, so far).

Then I selected the GNM project as a Binary, as stated in the doc, and all the images come out red:

![Screenshot from 2019-04-25 11-05-44](https://user-images.githubusercontent.com/650430/56723858-1a6b6f00-674a-11e9-9ed9-65172d9b53d8.png)

**Comment by raphink** [comment] 2019-04-25 09:07
When I click on the `0001` link, I can see the original image so I can tell that it's reading it well.

**Comment by chreul** [comment] 2019-04-25 13:40
From what I can see everything seems to work as intended. A red cross simply indicates that a step hasn't been performed for a page.
To be honest, there seems to be a bit of a misconception regarding the usage and capabilities of OCR4all on your part. It sounds like you've been expecting something like ABBYY on steroids where you throw in arbitrary data on one end and collect perfect results on the other :-). While we also would like historical OCR to work that way, I can't see this happening for the foreseeable future, especially when dealing with incunabula.
OCR4all is built to allow even non-technical users to independently perform OCR on even the earliest printed books, which is a very challenging task that often requires a significant amount of manual interaction, especially when almost perfect quality is desired.
If you are looking for mass digitization of historical material the [OCR-D project](https://github.com/ocr-d) (in progress), which you are probably already aware of, might be better suited to your needs. Don't get me wrong. You are more than welcome to use and test OCR4all and point out bugs or weaknesses. I just want to make sure that you are aware of the scope of the project.
Anyways, since the intial problem has been solved, I will close this issue.

**Closed by chreul** 2019-04-25 13:40 UTC
